;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-beginning-of-statement
        c-electric-colon
        c-electric-paren
        c-electric-star
        c-end-of-statement
        c-indent-line-or-region
        dired-mark
        dired-next-line
        dired-unmark
        indent-for-tab-command
        markdown-outdent-or-delete
        ))

(setq mc/cmds-to-run-once
      '(
        dabbrev-expand
        dired-toggle-read-only
        end-of-buffer
        find-file
        kbd-macro-query
        mac-mwheel-scroll
        mouse-minor-mode-menu
        mouse-select-window
        save-buffers-kill-terminal
        undefined
        wdired-finish-edit
        ))
