;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-beginning-of-statement
        c-electric-colon
        c-electric-paren
        c-end-of-statement
        c-indent-line-or-region
        indent-for-tab-command
        ))

(setq mc/cmds-to-run-once
      '(
        dabbrev-expand
        mac-mwheel-scroll
        mouse-minor-mode-menu
        mouse-select-window
        save-buffers-kill-terminal
        ))
