;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-beginning-of-statement
	c-electric-paren
	c-end-of-statement
	))

(setq mc/cmds-to-run-once
      '(
	))
